// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UrlShortenerNet;

namespace UrlShortenerNet.Migrations
{
    [DbContext(typeof(UrlShortnerContext))]
    partial class UrlShortnerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("UrlShortenerNet.Models.Redirect", b =>
                {
                    b.Property<int>("RedirectId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("EndPoint");

                    b.Property<string>("EntryPoint");

                    b.Property<DateTime?>("ExpireDate");

                    b.HasKey("RedirectId");

                    b.ToTable("Redirects");
                });
#pragma warning restore 612, 618
        }
    }
}
